// <auto-generated/>

namespace Game.Entities.Modifiers
{

    public partial class HeavyAttackModifier
    {
        public HeavyAttackModifier() { }
    }

    public partial class HeroKillModifier
    {
        public HeroKillModifier() { }
    }

    public partial class HealingPotionModifier
    {
        public HealingPotionModifier() { }
    }

    public partial class SprintModifier
    {
        public SprintModifier() { }
    }

}
namespace Game.Entities.Modifiers.Equipments
{

    public partial class HelmetModifier
    {
        public HelmetModifier() { }
    }

}
